# Generated by Django 2.1.3 on 2018-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20181213_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('Customer_Email', models.EmailField(default=None, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='id',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email_id',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
